# Generated by Django 6.0.3 on 2026-06-04 15:41

import agrivall.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=agrivall.models.upload_producto)),
                ('peso_kg', models.IntegerField()),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='TipoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cultivos', 'Cultivos'), ('ecología', 'Ecología'), ('cursos', 'Cursos')], default='libre', max_length=255)),
            ],
            options={
                'db_table': 'tipo_post',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('carrito', 'Carrito'), ('confirmado', 'Confirmado'), ('iniciado', 'Iniciado'), ('en proceso', 'En proceso'), ('reparto', 'Reparto'), ('finalizado', 'Finalizado')], default='carrito', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('bizum', 'Bizum'), ('transferencia', 'Transferencia')], max_length=50, null=True)),
                ('codigo_seguimiento', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('usuario_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.IntegerField(default=1)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='agrivall.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='agrivall.producto')),
            ],
            options={
                'db_table': 'lineas_pedido',
            },
        ),
        migrations.CreateModel(
            name='SemanaCasilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('numero_sem', models.IntegerField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('pre-reserva', 'Pre-reserva'), ('reservado', 'Reservado')], default='libre', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descriptor', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'semanas_casilla',
                'ordering': ['ano', 'numero_sem'],
                'unique_together': {('ano', 'numero_sem')},
            },
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('noticia', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=agrivall.models.upload_blog)),
                ('fecha_public', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='agrivall.tipopost')),
            ],
            options={
                'db_table': 'posts_blog',
            },
        ),
    ]
